general {
        lock_cmd = pidof hyprlock || hyprlock       # Comando per bloccare la sessione
        before_sleep_cmd = loginctl lock-session    # Blocca prima che il PC vada in sospensione
        after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # Riaccende i monitor al risveglio
}

# 1. Riduzione luminosità (Pre-timeout)
listener {
         timeout = 150                                # 2.5 minuti
         on-timeout = brightnessctl -s set 10         # Salva la luminosità attuale e la mette al 10%
         on-resume = brightnessctl -r                 # Ripristina la luminosità precedente
}

# 2. Blocco dello schermo
listener {
         timeout = 300                                # 5 minuti
         on-timeout = loginctl lock-session           # Chiama il comando di blocco globale
}

listener {
          timeout = 500                            # in seconds.
          on-timeout = notify-send "You are idle!" # command to run when timeout has passed.
          on-resume = notify-send "Welcome back!"  # command to run when activity is detected after timeout has fired.
}

# 3. Spegnimento Monitor (DPMS)
listener {
         timeout = 600                                                             # 10 minuti
         on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'       # Spegne l'HannStar e il Samsung
         on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'         # Li riaccende al movimento del mouse
}

# 4. standby
listener {
         timeout = 1800                                # 30min
         on-timeout = systemctl suspend                # suspend pc
}