background {
    monitor =
    path = screenshot # Prende uno screenshot sfocato del tuo desktop attuale
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.7
}

# OROLOGIO (Grande al centro)
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(33, 204, 255, 1.0) # Azzurro Neon coerente con i bordi delle finestre
    font_size = 80
    font_family = JetBrains Mono Nerd Font ExtraBold
    position = 0, 150
    halign = center
    valign = center
}

# DATA
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d %B %Y')"
    color = rgba(255, 255, 255, 0.8)
    font_size = 20
    font_family = JetBrains Mono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}

# CAMPO PASSWORD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true
    
    # Gradienti azzurro/verde neon presi da theme.lua
    outer_color = rgba(33, 204, 255, 1.0)
    check_color = rgba(0, 255, 153, 1.0)
    fail_color = rgba(255, 85, 85, 1.0)
    inner_color = rgba(30, 30, 30, 0.7)
    font_color = rgba(255, 255, 255, 0.9)
    
    fade_on_empty = false
    placeholder_text = <i>Inserisci la password...</i>
    hide_input = false
    
    position = 0, -50
    halign = center
    valign = center
}